version: "3.8"

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-1
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root123

  tienda:
    image: nginx:alpine
    container_name: tienda-urbana-1
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - db   # espera a que MySQL arranque

  db:
    image: mysql:8.0
    container_name: mysql-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: tienda_db
      MYSQL_USER: tienda_user
      MYSQL_PASSWORD: tienda123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

  

  
